name: AudiRED Structurizr to PNG action
description: An action created to convert dsl files to png outputs
inputs:
  image_output_folder:
    description: "preferred output folder for images - folder must exist"
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Check for .dsl files
      shell: bash
      id: dsl_check
      run: |
        if find docs -type f -name "*.dsl" | grep -q .; then
          echo "has_dsl_files=true" >> $GITHUB_OUTPUT
        else
          echo "has_dsl_files=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Skipping Structurizr to PNG
      if: steps.dsl_check.outputs.has_dsl_files == 'false'
      shell: bash
      run: echo "Skipping structurizr to png as no dsl files exist."

    - name: Run structurizr-to-png container
      if: steps.dsl_check.outputs.has_dsl_files == 'true'
      shell: bash
      run: |
        output_str=""
        if [ -n "${{ inputs.image_output_folder }}" ]; then
          output_str="--output ${{ inputs.image_output_folder }}"
        fi
        docker pull --quiet extenda/structurizr-to-png
        docker run --rm \
            -v "${PWD}/docs:/docs" \
            extenda/structurizr-to-png "$output_str"